stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/  
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose

build:
  stage: build
  script:
    - docker-compose build
  tags:
    - docker

test:
  stage: test
  image: python:3.10 
  before_script:
    - pip install --upgrade pip 
    - pip install -r requirements.txt  
  script:
    - docker-compose up -d
    - sleep 30
    - pytest tests/
    - docker-compose down
  tags:
    - docker
  only:
    - main 
